In [1]:
#Нормировка матрицы
import numpy as np
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[  8.39134734e+00   1.55384365e+01  -8.82911684e-01 ...,   3.62247922e+01
   -1.03344903e+01  -6.81956059e-01]
 [ -2.63484634e+01   4.13311500e+00  -3.54648380e+00 ...,  -1.07870585e+00
   -3.17640000e+00   1.90466279e+00]
 [  9.92900244e+00   1.28108207e+00   5.38900075e+00 ...,  -1.13355586e+01
    1.41350419e+01   9.24395328e+00]
 ..., 
 [ -1.19193213e+01   4.14367897e+00  -9.83689767e+00 ...,   2.05866105e+01
    1.32560397e+01  -1.15775863e+01]
 [  6.42202889e-01  -9.33235585e+00   1.15816485e+01 ...,   1.21746931e+01
   -1.80375505e+00  -1.13451559e+01]
 [  4.48853992e+00  -4.11673247e-01  -1.82957567e-02 ...,  -1.04227444e+01
   -1.27524507e+01   1.23571913e+01]]


In [2]:
#Код для самопроверки
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print(X_norm)

[[ 0.72135759  1.53105732 -0.13761414 ...,  3.56845339 -1.0565304
  -0.13185965]
 [-2.64959823  0.3638527  -0.40709422 ..., -0.22158035 -0.35878962
   0.1271653 ]
 [ 0.87056299  0.07197965  0.49693051 ..., -1.26367613  1.32865753
   0.8621245 ]
 ..., 
 [-1.24947544  0.36493381 -1.04351071 ...,  1.97961483  1.24297606
  -1.22295201]
 [-0.0305758  -1.01418471  1.12345576 ...,  1.12496439 -0.22498991
  -1.19967633]
 [ 0.34265111 -0.10125455 -0.05013884 ..., -1.17093425 -1.29222309
   1.17388527]]


In [4]:
#Операции над элементами матрицы
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5], dtype=int64),)


In [7]:
#Объединение матриц
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)
print()
print('Объединённая матрица:')
AB = np.vstack((A, B))
print(AB)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

Объединённая матрица:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
